# -*- coding: utf-8 -*-
"""24159091_advancedtask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwbXQz1dS9YN9Zzac9CzFJTht2kdhP3N
"""

#Name - Bisistha Patra
#Student ID - 24159091

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#the new dataset is in tsv file format, and we need to combine the train and test dataset,
#make changes to the reviewID column name (currently - Unnamed:0) before proceeding to dataset analysis

train = pd.read_csv("/content/drugLibTrain_raw.tsv", sep = "\t")
test = pd.read_csv("/content/drugLibTest_raw.tsv", sep = "\t")

#combining the training and testing dataset
df = pd.concat([train, test], ignore_index=True)

#renamining the column Unnamed: 0 to reviewID
df.rename(columns={'Unnamed: 0': 'reviewID'}, inplace=True)

#dataset analysis
df.dtypes
df.info()
df.describe()

#finding the count of nan/missing values in the dataset
df.isna().sum()

#dropping nan/missing values based rows in the columns - "benefitsReview" and "sideEffectsReview", as these are the primary columns for the pathway task
df = df.dropna(subset=['benefitsReview', 'sideEffectsReview']).copy()
#ignored the 11 missing values in "commentsReview" column as it is not used -
#and we cannot drop another 11 rows which do contain the benefits and sideEffcets reviews

df.info()

from wordcloud import WordCloud
import numpy as np

# Set style
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

plt.figure()
sns.countplot(data=df, x='rating', palette='plasma')
plt.title('Distribution of Overall Rating (1-10)')
plt.xlabel('Overall Rating')
plt.ylabel('Count')
plt.savefig('overall_rating_dist.png')
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

sns.countplot(data=df, x='effectiveness', order=[
    'Ineffective', 'Marginally Effective', 'Moderately Effective',
    'Considerably Effective', 'Highly Effective'], ax=axes[0], palette='Blues')
axes[0].set_title('Effectiveness Rating Distribution')
axes[0].tick_params(axis='x', rotation=45)

sns.countplot(data=df, x='sideEffects', order=[
    'No Side Effects', 'Mild Side Effects', 'Moderate Side Effects',
    'Severe Side Effects', 'Extremely Severe Side Effects'], ax=axes[1], palette='Reds')
axes[1].set_title('Side Effects Severity Distribution')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.savefig('aspect_ratings_dist.png')
plt.show()

# Create ordered categories
eff_order = ['Ineffective', 'Marginally Effective', 'Moderately Effective',
             'Considerably Effective', 'Highly Effective']
se_order = ['No Side Effects', 'Mild Side Effects', 'Moderate Side Effects',
            'Severe Side Effects', 'Extremely Severe Side Effects']

crosstab = pd.crosstab(df['effectiveness'], df['sideEffects'])
crosstab = crosstab.loc[eff_order, se_order]

plt.figure(figsize=(10, 8))
sns.heatmap(crosstab, annot=True, fmt='d', cmap='YlOrRd')
plt.title('Heatmap: Effectiveness vs Side Effects Severity')
plt.ylabel('Effectiveness')
plt.xlabel('Side Effects')
plt.savefig('effectiveness_vs_sideeffects_heatmap.png')
plt.show()

# Word cloud for benefitsReview (positive effectiveness words)
high_eff_text = ' '.join(df[df['effectiveness'].isin(['Highly Effective', 'Considerably Effective'])]['benefitsReview'])
wordcloud_eff = WordCloud(width=800, height=400, background_color='white', colormap='Greens').generate(high_eff_text)

plt.figure(figsize=(12, 6))
plt.imshow(wordcloud_eff, interpolation='bilinear')
plt.axis('off')
plt.title('Common Words in Highly/Considerably Effective Reviews')
plt.savefig('wordcloud_effectiveness_positive.png')
plt.show()

# Word cloud for severe side effects
severe_se_text = ' '.join(df[df['sideEffects'].isin(['Severe Side Effects', 'Extremely Severe Side Effects'])]['sideEffectsReview'])
wordcloud_se = WordCloud(width=800, height=400, background_color='white', colormap='Reds').generate(severe_se_text)

plt.figure(figsize=(12, 6))
plt.imshow(wordcloud_se, interpolation='bilinear')
plt.axis('off')
plt.title('Common Words in Severe/Extremely Severe Side Effects Reviews')
plt.savefig('wordcloud_sideeffects_severe.png')
plt.show()