# -*- coding: utf-8 -*-
"""advancedAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JrV70YK_NSg1ByKU3zk5X11mhQt3InC1
"""

#Name - Bisistha Patra
#Student ID - 24159091

#importing all the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#loading the combined dataset, downloaded from kaggle onto the system
df = pd.read_csv("/content/my_data")
df

#dataset analysis
# df.describe()
# df.info()

df.isna().sum()
#there are 1194 nan values - missing values is the column of condition
#we can remove them from the dataset as the first preprocessing step

df = df.dropna()
df
#new size of the dataset - 213869 rows × 7 columns

#now out of all the columns in the dataset, we do not need - date and usefulCount columns for the first task,
#hence we remove both of those columns from the dataset - reducing dimensionality

df = df.drop(columns=['date', 'usefulCount'])
df
#new dataset size - 213869 rows × 5 columns

plt.figure(figsize=(15, 7))
#more cool tone laternative to plasma - "magma"
ax = sns.countplot(data=df, x='rating', palette="plasma", hue='rating', legend=False)

for container in ax.containers:
    ax.bar_label(container, color='black', padding=3)

plt.title('Distribution of Ratings')
plt.xlabel('Rating')
plt.ylabel('Count')

# Show the figure
plt.show()
plt.savefig('rating_distribution_labeled.png')

grouped_counts = df['rating'].apply(lambda x: '1-5' if x <= 5 else str(int(x)))

#getting the counts and sort them according to your preferred order
order = ['1-5', '6', '7', '8', '9', '10']
table = grouped_counts.value_counts().reindex(order).to_frame(name='Total Count')

#adding percentage column for better comparison
table['Percentage'] = (table['Total Count'] / table['Total Count'].sum() * 100).round(2).astype(str) + '%'

print(table)
#the table shows that if we group ratings 1 to 5 as 0 and 6 to 10 as 1 - there will be a class imbalance,
#that may cause the naive bayes to be biased as word occurances for class 1 will be higher

#hence, for the dataset to have even representation of both classes and the fact that the size is more than 200k,
#we can consider undersampling from the rating 6 to 10, to match the count of the ratings 1 to 5